#!/bin/sh

if [ "x$1" = x-a ]; then
    apps=`ls definitions | sed -n 's/\.m4$//p'`
elif [ $# -gt 0 ]; then
    apps=$*
else
    echo "Usage: generate-app [-a] | <appName> ..." >&2
fi

for app in $apps; do
    echo "Generating app: $app"
    rm -rf output/ui-$app
    mkdir -p output/ui-$app
    (
	cd template
	find . -type d -print | while read dir; do
	    test x$dir = x. || mkdir ../output/ui-$app/$dir
	done
	find . -type f -print | while read file; do
	    if echo $file | egrep '\.(svg|png)' > /dev/null; then
		echo "  Copying $file"
		cp $file ../output/ui-$app/$file
	    else
		echo "  Converting $file"
		cat ../definitions/$app.m4 $file | m4 > ../output/ui-$app/$file
	    fi
	done
    )
done
