#!/bin/sh

if [ "x$1" = x-a ]; then
    apps=`ls definitions | sed -n 's/\.m4$//p'`
elif [ $# -gt 0 ]; then
    apps=$*
else
    echo "Usage: generate-app [-a] | <appName> ..." >&2
fi

for app in $apps; do
    echo "Generating app: $app"
    rm -rf output/ui-$app
    mkdir -p output/ui-$app
    (
	cd template
	dest=../output/ui-$app
	find . -type d -print | while read dir; do
	    test x$dir = x. || mkdir $dest/$dir
	done
	find . -type f -print | while read file; do
	    echo "  Converting $file"
	    cat ../definitions/$app.m4 $file | m4 > $dest/$file
	done
	mkdir $dest/icons
	cp ../definitions/$app.svg $dest/icons/app.svg
	convert -size 14x14 $dest/icons/app.svg $dest/icons/app.png
    )
done
